-- Auteur : HANI Sidi-Walid
-- Projet Banque PL/SQL
create table client(
  id number generated by default on null as identity,
  civilite varchar2(10),
  nom varchar2(80) not null,
  prenom varchar2(80) not null,
  date_naissance date,
  adresse1 varchar2(200) not null,
  adresse2 varchar2(200),
  code_postal varchar2(16) not null,
  ville varchar2(80) not null,
  pays varchar2(80) not null,
  email varchar2(120),
  telephone varchar2(32),
  id_national varchar2(64),
  type_piece varchar2(30),
  no_piece varchar2(64),
  date_exp_piece date,
  kyc_statut varchar2(10) default 'PENDING' not null,
  kyc_date date,
  created_at date default sysdate not null,
  updated_at date,
  constraint pk_client primary key(id),
  constraint uq_client_email unique(email),
  constraint uq_client_idnat unique(id_national),
  constraint ck_client_kyc check (kyc_statut in ('OK','KO','PENDING'))
);

create table compte(
  id number generated by default on null as identity,
  client_id number not null,
  numero varchar2(32) not null,
  devise char(3) default 'EUR' not null,
  solde number(18,2) default 0 not null,
  etat varchar2(16) default 'OUVERT' not null,
  constraint pk_compte primary key(id),
  constraint uq_compte_numero unique(numero),
  constraint fk_compte_client foreign key(client_id) references client(id)
);

create table txn(
  id_txn varchar2(64) primary key,
  source varchar2(16),
  type_txn varchar2(16),
  montant number(18,2),
  devise char(3),
  debit number not null,
  credit number not null,
  statut varchar2(16),
  raison varchar2(200),
  constraint fk_txn_debit foreign key(debit) references compte(id),
  constraint fk_txn_credit foreign key(credit) references compte(id)
);

create table gl(
  id number generated by default on null as identity primary key,
  id_txn varchar2(64) not null,
  compte_id number not null,
  montant number(18,2) not null,
  dc char(1) not null,
  val_dt date default sysdate,
  constraint fk_gl_txn foreign key(id_txn) references txn(id_txn),
  constraint fk_gl_compte foreign key(compte_id) references compte(id),
  constraint ck_gl_dc check (dc in ('D','C'))
);

create table paiement_in(
  id number generated by default on null as identity primary key,
  fichier varchar2(64),
  ext_ref varchar2(64),
  debit_no varchar2(32),
  credit_no varchar2(32),
  montant number(18,2),
  devise char(3),
  statut varchar2(16) default 'RECU',
  raison varchar2(200),
  id_txn varchar2(64),
  constraint uq_pyin unique(fichier, ext_ref)
);

create table ext_conf(
  ref_ext varchar2(64) primary key,
  id_txn varchar2(64) not null,
  montant number(18,2),
  constraint fk_ext_txn foreign key(id_txn) references txn(id_txn)
);

create table recon_ex(
  id number generated by default on null as identity primary key,
  ref_ext varchar2(64),
  id_txn varchar2(64),
  type_ex varchar2(16),
  note varchar2(200),
  etat varchar2(16) default 'NOUVEAU'
);

create table stp_etat(
  id number generated by default on null as identity primary key,
  objet varchar2(16),
  ref varchar2(64),
  etape varchar2(16),
  statut varchar2(8),
  note varchar2(300),
  ts date default sysdate
);

create table produit_pret(
  id number generated by default on null as identity primary key,
  nom varchar2(64) not null,
  taux number(8,4) not null,
  frequence varchar2(16) not null,
  duree_mois number not null,
  constraint uq_produit_pret_nom unique(nom)
);

create table pret(
  id number generated by default on null as identity primary key,
  compte_id number not null,
  produit_id number not null,
  principal number(18,2) not null,
  taux number(8,4) not null,
  debut date not null,
  constraint fk_pret_compte foreign key(compte_id) references compte(id),
  constraint fk_pret_produit foreign key(produit_id) references produit_pret(id)
);

create table echeance(
  id number generated by default on null as identity primary key,
  pret_id number not null,
  no_echeance number not null,
  date_echeance date not null,
  principal number(18,2),
  interet number(18,2),
  total number(18,2),
  statut varchar2(16) default 'A_PAYER',
  constraint fk_ech_pret foreign key(pret_id) references pret(id)
);

create table audit_log(
  id number generated by default on null as identity primary key,
  who varchar2(64),
  evt varchar2(32),
  ref varchar2(64),
  msg varchar2(4000),
  ts date default sysdate
);

create index ix_txn_statut on txn(statut);
create index ix_pyin_statut on paiement_in(statut);
create index ix_gl_txn on gl(id_txn);
